export default [
  { text: "臺北市", value: "Taipei", code: "TPE" },
  { text: "新北市", value: "NewTaipei", code: "NWT" },
  { text: "桃園市", value: "Taoyuan", code: "TAO" },
  { text: "臺中市", value: "Taichung", code: "TXG" },
  { text: "臺南市", value: "Tainan", code: "TNN" },
  { text: "高雄市", value: "Kaohsiung", code: "KHH" },
  { text: "基隆市", value: "Keelung", code: "KEE" },
  { text: "新竹市", value: "Hsinchu", code: "HSZ" },
  { text: "新竹縣", value: "HsinchuCounty", code: "HSQ" },
  { text: "苗栗縣", value: "MiaoliCounty", code: "MIA" },
  { text: "彰化縣", value: "ChanghuaCounty", code: "CHA" },
  { text: "南投縣", value: "NantouCounty", code: "NAN" },
  { text: "雲林縣", value: "YunlinCounty", code: "YUN" },
  { text: "嘉義縣", value: "ChiayiCounty", code: "CYQ" },
  { text: "嘉義市", value: "Chiayi", code: "CYI" },
  { text: "屏東縣", value: "PingtungCounty", code: "PIF" },
  { text: "宜蘭縣", value: "YilanCounty", code: "ILA" },
  { text: "花蓮縣", value: "HualienCounty", code: "HUA" },
  { text: "臺東縣", value: "TaitungCounty", code: "TTT" },
  { text: "金門縣", value: "KinmenCounty", code: "KIN" },
  { text: "澎湖縣", value: "PenghuCounty", code: "PEN" },
  { text: "連江縣", value: "LienchiangCounty", code: "LIE" },
];
