export default [
  { text: "臺北市" },
  { text: "新北市" },
  { text: "桃園市" },
  { text: "臺中市" },
  { text: "臺南市" },
  { text: "高雄市" },
  { text: "基隆市" },
  { text: "新竹市" },
  { text: "嘉義市" },
  { text: "新竹縣" },
  { text: "苗栗縣" },
  { text: "彰化縣" },
  { text: "南投縣" },
  { text: "雲林縣" },
  { text: "嘉義縣" },
  { text: "屏東縣" },
  { text: "宜蘭縣" },
  { text: "花蓮縣" },
  { text: "臺東縣" },
  { text: "澎湖縣" },
  { text: "金門縣" },
  { text: "連江縣" },
];
